services:

  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    command: >
      postgres -c max_connections=400
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=game_server
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"

  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/game_server?sslmode=disable
    volumes:
      - .:/app
    command: >
      /app/run.sh
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_started
