"""empty message

Revision ID: c03306dbeac9
Revises:
Create Date: 2023-12-10 11:09:28.630801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c03306dbeac9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('player1', sa.String(length=256), nullable=True),
    sa.Column('player2', sa.String(length=256), nullable=True),
    sa.Column('next_player', sa.Enum('x', 'o', name='playermark'), nullable=True),
    sa.Column('winner', sa.String(length=256), nullable=True),
    sa.Column('board', postgresql.ARRAY(sa.String(length=17)), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'done', name='gamestatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_status'))

    op.drop_table('games')
    # ### end Alembic commands ###
